import "./style.css";
import Header from "./ui/Header/Header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-[#172a41]">
      
      <body  className="text-white">
        <Header />
        {children}
      </body>
    </html>
  )
}
